version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 targetpulse_project.wsgi:application
    volumes:
      - .:/app
      - static_data:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DEBUG=1

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  worker:
    build: .
    command: python manage.py runworker channels
    volumes:
      - .:/app
    depends_on:
      - redis

volumes:
  static_data: