# Generated by Django 4.2 on 2025-05-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetpulse', '0004_task_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'Обычный пользователь'), ('manager', 'Менеджер'), ('developer', 'Разработчик')], default='user', max_length=20),
        ),
    ]
