# Generated by Django 4.2 on 2025-05-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetpulse', '0007_notification_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='spent_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
