# Generated by Django 4.2 on 2025-05-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targetpulse', '0008_task_spent_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
